travis:
  secure:
    BINSTAR_TOKEN: lnAJMaFbbjA4t30Z+U+NLIxWRxwbi/rX9CQSLQZQlcIFc/9t3kYCCocfA1psz6fvEGY6Sw1ThjGt910lmuI7pCla6syONgCwIK0sy2zXPRtXAC7ZvU04B2iOgDWEw3D0VVAP4F4Vlt8kB8LjfsHMU/KGWllLBcQZwgeOPbmwgu4YNFLWoKdJ/IZd7v81Wc7UJOKImFyXjodmw8VZ4J6s6cWCS0kQY3aJujWVyjzISMaFveOr5U5jT+v/EIq+3cD6oDIEQR+MjrSpwWpHDPHPaEVjM3dGAf6BGNnXZZ9jsJgIWdk4aDlmcSKzPlxnqKHMPIUe0Iwlc5/7TcI4jW88+bFQXP3W41sjus5jATNy7H7crQFkygnUkLw9ugoxD7Tjb1j2HamcnL+ou8VsabbDlHldquisut6CbnvWm4WReBxt/Icairjv3cK79cgCLLZxjvmYImVNIllS5/G1eWLsfQ0mVk66u/DvZGyJMN1onujZppSCfaO819+Agz1sqH1G2679D6SRQX7Vncrh/gDRrDxYrCYa44YYaGpf6pV7ZvaZoThXBNeAFNYfqzedJFi0P+Fxc9SIfn0+fBWFSfFOQwliKwKh3ETHY+Q2KceLkFcP8x3a0rrr7Hjl0UJg366OBv+WBSJbV6JRXbXe9opjSC1GRIXA08dvnJ5Xl5iXCIk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
